# Generated by Django 3.2.15 on 2022-10-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_company_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='rating',
            field=models.IntegerField(blank=True, default=0, max_length=250),
        ),
    ]
