# Generated by Django 3.2.15 on 2022-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221004_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencer',
            old_name='username',
            new_name='instagram_id',
        ),
        migrations.AddField(
            model_name='influencer',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='influencer',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
